<a href="https://colab.research.google.com/github/Lomachynska/Django/blob/main/lab1_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.utils import to_categorical

# Завантаження та підготовка даних з датасету MNIST
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Перетворення даних для схожості з EMNIST
x_train = np.expand_dims(x_train, axis=-1)
x_test = np.expand_dims(x_test, axis=-1)

# Нормалізація значень пікселів
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

# Перетворення міток класів у формат one-hot
num_classes = len(np.unique(y_train))
y_train = to_categorical(y_train, num_classes)
y_test = to_categorical(y_test, num_classes)

# Створення моделі багатошарового персептрону
model = Sequential([
    Flatten(input_shape=(28, 28, 1)),  # Вирівнювання вхідних даних
    Dense(128, activation='relu'),   # Полно-зв'язаний шар з 128 нейронами та функцією активації ReLU
    Dense(num_classes, activation='softmax')  # Вихідний шар з кількістю нейронів, що відповідають кількості класів та функцією активації softmax
])

# Компіляція моделі
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Навчання моделі
history = model.fit(x_train, y_train, epochs=10, batch_size=32, validation_data=(x_test, y_test))


11490434/11490434 [==============================] - 0s 0us/step
Epoch 1/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2612 - accuracy: 0.9266 - val_loss: 0.1408 - val_accuracy: 0.9572
Epoch 2/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1149 - accuracy: 0.9666 - val_loss: 0.1017 - val_accuracy: 0.9693
Epoch 3/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0781 - accuracy: 0.9767 - val_loss: 0.0867 - val_accuracy: 0.9739
Epoch 4/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0585 - accuracy: 0.9818 - val_loss: 0.0821 - val_accuracy: 0.9742
Epoch 5/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0461 - accuracy: 0.9857 - val_loss: 0.0758 - val_accuracy: 0.9763
Epoch 6/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0365 - accuracy: 0.9887 - val_loss: 0.0734 - val_accuracy: 0.9786
Epoch 7/10
1875/1875 [==============================] - 7s 4ms/step - l

In [2]:
import numpy as np

class Environment:
    def __init__(self, grid_size):
        self.grid_size = grid_size
        self.state = (0, 0)  # Початковий стан
        self.goal = (grid_size-1, grid_size-1)  # Кінцевий стан

    def reset(self):
        self.state = (0, 0)  # Початковий стан
        return self.state

    def step(self, action):
        if action == 0:  # Рух вгору
            self.state = (max(0, self.state[0]-1), self.state[1])
        elif action == 1:  # Рух вниз
            self.state = (min(self.grid_size-1, self.state[0]+1), self.state[1])
        elif action == 2:  # Рух вліво
            self.state = (self.state[0], max(0, self.state[1]-1))
        elif action == 3:  # Рух вправо
            self.state = (self.state[0], min(self.grid_size-1, self.state[1]+1))

        reward = -1  # Нагорода за кожен крок

        if self.state == self.goal:
            reward = 0  # Нагорода за досягнення цілі

        return self.state, reward

class QLearningAgent:
    def __init__(self, num_actions, epsilon=0.1, alpha=0.1, gamma=0.9):
        self.num_actions = num_actions
        self.epsilon = epsilon  # Ймовірність випадкової дії
        self.alpha = alpha  # Крок навчання
        self.gamma = gamma  # Дисконтний фактор

        self.q_table = np.zeros((grid_size, grid_size, num_actions))  # Q-таблиця

    def choose_action(self, state):
        if np.random.uniform(0, 1) < self.epsilon:
            return np.random.choice(self.num_actions)  # Випадкова дія
        else:
            return np.argmax(self.q_table[state])  # Вибір дії з максимальним Q-значенням

    def update_q_table(self, state, action, reward, next_state):
        next_max = np.max(self.q_table[next_state])
        self.q_table[state][action] += self.alpha * (reward + self.gamma * next_max - self.q_table[state][action])

# Параметри
grid_size = 10
num_actions = 4
num_episodes = 1000

# Ініціалізація середовища та агента
env = Environment(grid_size)
agent = QLearningAgent(num_actions)

# Навчання
for episode in range(num_episodes):
    state = env.reset()
    done = False

    while not done:
        action = agent.choose_action(state)
        next_state, reward = env.step(action)
        agent.update_q_table(state, action, reward, next_state)
        state = next_state

        if state == env.goal:
            done = True

# Виведення оптимальної стратегії
optimal_policy = np.argmax(agent.q_table, axis=2)
print("Optimal Policy:")
print(optimal_policy)



Optimal Policy:
[[1 1 3 3 1 0 1 1 1 1]
 [1 1 1 3 3 1 1 0 1 1]
 [1 0 1 3 3 3 3 2 3 1]
 [3 1 1 1 1 1 3 1 1 1]
 [1 1 3 3 1 3 1 3 3 1]
 [1 1 3 3 1 3 1 1 1 1]
 [1 1 3 1 3 1 1 3 3 1]
 [1 1 1 3 3 1 1 1 1 1]
 [1 1 1 3 3 3 1 3 1 1]
 [2 3 3 3 3 3 3 3 3 0]]


In [4]:
class GameState:
    def __init__(self):
        # Ініціалізуємо початковий стан гри
        pass

    def actions(self):
        # Повертає список доступних дій у поточному стані гри
        # Припустимо, що цей метод повертає список доступних ходів
        return []

    def result(self, action):
        # Повертає новий стан гри, який виникає після виконання певної дії
        # Припустимо, що цей метод змінює стан гри згідно з вибраним дією
        pass

    def utility(self):
        # Обчислює корисність (виграш або програш) у поточному стані гри
        # Припустимо, що цей метод повертає числове значення, що відображає виграш або програш
        return 0

    def terminal_test(self):
        # Перевіряє, чи є поточний стан гри термінальним (кінцевим)
        # Припустимо, що цей метод повертає True або False
        return False


def minimax_decision(state):
    def max_value(state):
        if state.terminal_test():
            return state.utility()
        v = float('-inf')
        for action in state.actions():
            v = max(v, min_value(state.result(action)))
        return v

    def min_value(state):
        if state.terminal_test():
            return state.utility()
        v = float('inf')
        for action in state.actions():
            v = min(v, max_value(state.result(action)))
        return v

    best_action = None
    best_value = float('-inf')

    for action in state.actions():
        value = min_value(state.result(action))
        if value > best_value:
            best_value = value
            best_action = action

    return best_action


# Основний код
if __name__ == "__main__":
    initial_state = GameState()  # Ініціалізуємо початковий стан гри
    best_action = minimax_decision(initial_state)  # Знаходимо оптимальну дію для гравця
    print("Optimal action:", best_action)


Optimal action: None


In [7]:
import random

class ExpectimaxAgent:
    def getAction(self, gameState):
        """
        Вибір дії для даного стану гри.
        :param gameState: Поточний стан гри
        :return: Обрана дія
        """
        # Отримуємо доступні дії для Пакмена
        legalActions = self.getLegalActions(gameState)

        # Вибираємо одну з доступних дій випадковим чином
        action = random.choice(legalActions)

        return action

    def getLegalActions(self, gameState):
        """
        Повертає список доступних дій для даного стану гри.
        :param gameState: Поточний стан гри
        :return: Список доступних дій
        """
        # Реалізуйте логіку отримання доступних дій для Пакмена з поточного стану гри
        pass

    def getSuccessor(self, gameState, action):
        """
        Повертає наступний стан гри після виконання певної дії.
        :param gameState: Поточний стан гри
        :param action: Дія, яку виконує агент
        :return: Наступний стан гри
        """
        # Реалізуйте логіку отримання наступного стану гри після виконання певної дії
        pass

    def isTerminal(self, gameState):
        """
        Перевіряє, чи є поточний стан гри термінальним.
        :param gameState: Поточний стан гри
        :return: True, якщо гра закінчилася, інакше False
        """
        # Реалізуйте логіку перевірки, чи є поточний стан гри термінальним
        pass

    def getUtility(self, gameState):
        """
        Обчислює корисність (виграш або програш) для даного стану гри.
        :param gameState: Поточний стан гри
        :return: Числове значення, яке відображає корисність даного стану гри
        """
        # Реалізуйте логіку обчислення корисності (виграш або програш) для даного стану гри
        pass


In [8]:
def betterEvaluationFunction(currentGameState):
    """
    Оцінює поточний стан гри та повертає числове значення, яке відображає його привабливість для Пакмена.
    """
    # Отримання інформації про стан гри
    pacmanPosition = currentGameState.getPacmanPosition()
    foodGrid = currentGameState.getFood()
    capsules = currentGameState.getCapsules()
    ghostStates = currentGameState.getGhostStates()

    # Оцінка відстані до найближчої кульки
    closestFood = min([manhattanDistance(pacmanPosition, food) for food in foodGrid.asList()])

    # Оцінка кількості кульок та бігмаксів
    numFood = currentGameState.getNumFood()
    numCapsules = len(capsules)

    # Оцінка відстані до привидів
    ghostDistances = [manhattanDistance(pacmanPosition, ghost.getPosition()) for ghost in ghostStates]

    # Оцінка = відстань до найближчої кульки - кількість кульок - кількість бігмаксів + мінімальна відстань до привидів
    evaluation = closestFood - numFood - numCapsules + min(ghostDistances)

    return evaluation


In [9]:
class MiniMaxAgent:
    def getAction(self, gameState):
        """
        Вибір дії для даного стану гри.
        :param gameState: Поточний стан гри
        :return: Обрана дія
        """
        # Реалізуйте алгоритм MiniMax тут
        pass


In [10]:
for num_ghosts in range(1, 6):
    print(f"Number of Ghosts: {num_ghosts}")
    # Запуск гри з заданою кількістю привидів та агентом MiniMax
    # Отримання результатів та їх аналіз


Number of Ghosts: 1
Number of Ghosts: 2
Number of Ghosts: 3
Number of Ghosts: 4
Number of Ghosts: 5


In [2]:
class GameState:
    def __init__(self, pacman_pos, ghost_pos, food_positions):
        self.pacman_pos = pacman_pos
        self.ghost_pos = ghost_pos
        self.food_positions = food_positions

    def is_terminal(self):
        return len(self.food_positions) == 0 or self.pacman_pos == self.ghost_pos

    def get_legal_moves(self, agent):
        if agent == 'pacman':
            return ['up', 'down', 'left', 'right']
        elif agent == 'ghost':
            # Assuming ghost can move in all directions
            return ['up', 'down', 'left', 'right']

    def generate_successor(self, agent, action):
        if agent == 'pacman':
            new_pos = self.pacman_pos.copy()
            if action == 'up':
                new_pos[0] -= 1
            elif action == 'down':
                new_pos[0] += 1
            elif action == 'left':
                new_pos[1] -= 1
            elif action == 'right':
                new_pos[1] += 1
            return GameState(new_pos, self.ghost_pos, self.food_positions)
        elif agent == 'ghost':
            # Similar logic for ghost's movement
            pass

    def evaluate(self):
        # Simple evaluation function: number of remaining food pellets
        return len(self.food_positions)

def minimax(state, depth, maximizing_player):
    if depth == 0 or state is None or state.is_terminal():
        return state.evaluate() if state is not None else 0

    if maximizing_player:
        max_eval = float('-inf')
        for move in state.get_legal_moves('pacman'):
            successor = state.generate_successor('pacman', move)
            eval = minimax(successor, depth - 1, False)
            max_eval = max(max_eval, eval)
        return max_eval
    else:
        min_eval = float('inf')
        for move in state.get_legal_moves('ghost'):
            successor = state.generate_successor('ghost', move)
            eval = minimax(successor, depth - 1, True)
            min_eval = min(min_eval, eval)
        return min_eval

# Example usage
initial_state = GameState(pacman_pos=[0, 0], ghost_pos=[3, 3], food_positions=[[1, 1], [2, 2], [3, 1]])
best_score = minimax(initial_state, depth=3, maximizing_player=True)
print("Best score:", best_score)


Best score: 0


In [4]:
from game import MultiAgentSearchAgent, GameState

class AlphaBetaAgent(MultiAgentSearchAgent):
    def getAction(self, gameState: GameState) -> str:
        alpha = float("-inf")
        beta = float("inf")
        bestScore = float("-inf")
        bestAction = None

        for action in gameState.getLegalActions(0):  # 0 - індекс Pacman
            successorState = gameState.generateSuccessor(0, action)
            score = self.minValue(successorState, 0, 1, alpha, beta)
            if score > bestScore:
                bestScore = score
                bestAction = action
            alpha = max(alpha, bestScore)

        return bestAction

    def maxValue(self, state: GameState, depth: int, alpha: float, beta: float) -> float:
        if state.isWin() or state.isLose() or depth == self.depth:
            return self.evaluationFunction(state)

        value = float("-inf")
        for action in state.getLegalActions(0):  # 0 - індекс Pacman
            successorState = state.generateSuccessor(0, action)
            value = max(value, self.minValue(successorState, depth, 1, alpha, beta))
            if value >= beta:
                return value
            alpha = max(alpha, value)
        return value

    def minValue(self, state: GameState, depth: int, agentIndex: int, alpha: float, beta: float) -> float:
        if state.isWin() or state.isLose() or depth == self.depth:
            return self.evaluationFunction(state)

        value = float("inf")
        for action in state.getLegalActions(agentIndex):
            successorState = state.generateSuccessor(agentIndex, action)
            if agentIndex == state.getNumAgents() - 1:
                value = min(value, self.maxValue(successorState, depth + 1, alpha, beta))
            else:
                value = min(value, self.minValue(successorState, depth, agentIndex + 1, alpha, beta))
            if value <= alpha:
                return value
            beta = min(beta, value)
        return value


ModuleNotFoundError: No module named 'game'